"""Generates the shared cinematic-grade 3D LUT used by render_pipeline.py.

Run manually whenever the grade needs retuning:

    python scripts/generate_luts.py

This bakes a filmic S-curve (soft highlight rolloff, lifted blacks), a
subtle teal-shadow/warm-highlight split-tone, and a mild luma-preserving
saturation boost into a standard 33-point .cube file. Applied via FFmpeg's
lut3d filter on top of every style preset's own color filter so all
presets read as if shot on the same stock, instead of each preset's
different eq/colorchannelmixer math producing a different color response.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "assets" / "luts" / "cinematic_film.cube"
LUT_SIZE = 33

CONTRAST_STRENGTH = 0.35
BLACK_LIFT = 0.025
SATURATION = 1.08
SPLIT_TONE_STRENGTH = 0.02

LUMA = np.array([0.2126, 0.7152, 0.0722])


def s_curve(x: np.ndarray, strength: float) -> np.ndarray:
    """Endpoint-preserving filmic S-curve: boosts midtone contrast, softly
    rolls off toward 0 and 1 instead of clipping."""
    centered = x - 0.5
    return 0.5 + centered * (1 + strength) / (1 + strength * np.abs(2 * centered))


def build_lut() -> np.ndarray:
    coords = np.linspace(0.0, 1.0, LUT_SIZE)
    r, g, b = np.meshgrid(coords, coords, coords, indexing="ij")
    rgb = np.stack([r, g, b], axis=-1)

    graded = s_curve(rgb, CONTRAST_STRENGTH)
    graded = BLACK_LIFT + graded * (1 - BLACK_LIFT)

    luma = graded @ LUMA
    shadow_w = np.clip(1 - luma / 0.5, 0, 1)
    highlight_w = np.clip((luma - 0.5) / 0.5, 0, 1)

    split = np.zeros_like(graded)
    split[..., 0] = highlight_w * SPLIT_TONE_STRENGTH - shadow_w * (SPLIT_TONE_STRENGTH * 0.5)
    split[..., 1] = highlight_w * (SPLIT_TONE_STRENGTH * 0.25)
    split[..., 2] = shadow_w * SPLIT_TONE_STRENGTH - highlight_w * (SPLIT_TONE_STRENGTH * 0.5)
    graded = graded + split

    luma2 = np.clip(graded, 0, 1) @ LUMA
    sat_factor = SATURATION * (1 - 0.3 * highlight_w)
    graded = luma2[..., None] + (graded - luma2[..., None]) * sat_factor[..., None]

    return np.clip(graded, 0.0, 1.0)


def write_cube(lut: np.ndarray, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        handle.write("# Cinematic film emulation LUT (generated by scripts/generate_luts.py)\n")
        handle.write(f"LUT_3D_SIZE {LUT_SIZE}\n")
        # .cube format iterates red fastest, then green, then blue.
        for bi in range(LUT_SIZE):
            for gi in range(LUT_SIZE):
                for ri in range(LUT_SIZE):
                    rr, gg, bb = lut[ri, gi, bi]
                    handle.write(f"{rr:.6f} {gg:.6f} {bb:.6f}\n")


if __name__ == "__main__":
    write_cube(build_lut(), OUTPUT_PATH)
    print(f"Wrote {OUTPUT_PATH} ({LUT_SIZE}x{LUT_SIZE}x{LUT_SIZE})")
