import {defineField, defineType} from 'sanity'

export const tour = defineType({
  name: 'tour',
  title: 'Goldmoon Tour',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Tour Title',
      type: 'string',
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {source: 'title', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'images',
      title: 'Tour Images',
      type: 'array',
      of: [
        {
          type: 'image',
          options: {hotspot: true},
          fields: [
            defineField({
              name: 'alt',
              title: 'Alt Text',
              type: 'string',
              validation: (rule) => rule.max(120),
            }),
          ],
        },
      ],
      validation: (rule) => rule.min(2).max(12),
    }),
    defineField({
      name: 'category',
      title: 'Tour Category',
      type: 'string',
      description: 'Used by the n8n workflow to pick a fitting video style automatically.',
      options: {
        list: [
          {title: 'Nile Cruise', value: 'nile_cruise'},
          {title: 'Desert Safari', value: 'desert_safari'},
          {title: 'Ancient & Historical', value: 'ancient_historical'},
          {title: 'Beach & Red Sea', value: 'beach_red_sea'},
          {title: 'City & Cultural', value: 'city_cultural'},
          {title: 'Luxury & VIP', value: 'luxury_vip'},
          {title: 'Adventure', value: 'adventure'},
        ],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'text_scene_1',
      title: 'Video Hook Text',
      type: 'string',
      description: 'English only. Max 60 characters.',
      validation: (rule) => rule.required().max(60),
    }),
    defineField({
      name: 'text_scene_2',
      title: 'Video CTA Text',
      type: 'string',
      description: 'English only. Max 60 characters.',
      validation: (rule) => rule.required().max(60),
    }),
    defineField({
      name: 'bg_music',
      title: 'Background Music',
      type: 'string',
      options: {
        list: [
          {title: 'Desert Ambient', value: 'desert_ambient'},
          {title: 'Luxury Chill', value: 'luxury_chill'},
          {title: 'Cinematic Epic', value: 'cinematic_epic'},
          {title: 'Arab Trailer', value: 'arab_trailer'},
          {title: 'Vlog Energetic', value: 'vlog_energetic'},
          {title: 'Cairo Nights', value: 'cairo_nights'},
          {title: 'Egyptian Desert', value: 'egyptian_desert'},
          {title: 'Desert Travels', value: 'desert_travels'},
          {title: 'Ancient Mystique', value: 'ancient_mystique'},
          {title: 'Ancient Empire', value: 'ancient_empire'},
        ],
        layout: 'radio',
      },
      initialValue: 'luxury_chill',
    }),
    defineField({
      name: 'style',
      title: 'Video Style',
      type: 'string',
      description: 'Visual preset applied when rendering this tour video.',
      options: {
        list: [
          {title: 'Luxury Gold', value: 'luxury_gold'},
          {title: 'Cinematic Dark', value: 'cinematic_dark'},
          {title: 'Modern Vibe', value: 'modern_vibe'},
          {title: 'Minimal Clean', value: 'minimal_clean'},
          {title: 'Vintage Film', value: 'vintage_film'},
          {title: 'Desert Safari', value: 'desert_safari'},
          {title: 'Night Chill', value: 'night_chill'},
          {title: 'Dreamy Soft', value: 'dreamy_soft'},
          {title: 'Golden Hour', value: 'golden_hour'},
          {title: 'Editorial Mono', value: 'editorial_mono'},
        ],
        layout: 'dropdown',
      },
      initialValue: 'desert_safari',
    }),
    defineField({
      name: 'transition',
      title: 'Scene Transition',
      type: 'string',
      description: 'Optional. Leave unset for a randomly chosen transition each render.',
      options: {
        list: [
          {title: 'Fade', value: 'fade'},
          {title: 'Fade to Black', value: 'fadeblack'},
          {title: 'Fade to White', value: 'fadewhite'},
          {title: 'Dissolve', value: 'dissolve'},
          {title: 'Wipe Left', value: 'wipeleft'},
          {title: 'Wipe Right', value: 'wiperight'},
          {title: 'Wipe Up', value: 'wipeup'},
          {title: 'Wipe Down', value: 'wipedown'},
          {title: 'Slide Left', value: 'slideleft'},
          {title: 'Slide Right', value: 'slideright'},
          {title: 'Slide Up', value: 'slideup'},
          {title: 'Slide Down', value: 'slidedown'},
          {title: 'Smooth Left', value: 'smoothleft'},
          {title: 'Smooth Right', value: 'smoothright'},
          {title: 'Smooth Up', value: 'smoothup'},
          {title: 'Smooth Down', value: 'smoothdown'},
          {title: 'Circle Open', value: 'circleopen'},
          {title: 'Circle Close', value: 'circleclose'},
          {title: 'Radial', value: 'radial'},
          {title: 'Diagonal Top-Left', value: 'diagtl'},
          {title: 'Diagonal Bottom-Right', value: 'diagbr'},
        ],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'text_animation',
      title: 'Text Entrance Animation',
      type: 'string',
      description: 'Optional. Leave unset for a randomly chosen animation each render.',
      options: {
        list: [
          {title: 'Fade', value: 'fade'},
          {title: 'Slide Up', value: 'slide_up'},
          {title: 'Slide Down', value: 'slide_down'},
          {title: 'Rise + Fade', value: 'rise_fade'},
        ],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'text_style',
      title: 'Text Style',
      type: 'object',
      description: 'Optional overlay text styling, layered on top of the Video Style preset.',
      options: {collapsible: true, collapsed: true},
      fields: [
        defineField({
          name: 'mode',
          title: 'Style Mode',
          type: 'string',
          description: 'Optional. Leave unset to use the Video Style preset\'s own text look.',
          options: {
            list: [
              {title: 'Minimalist', value: 'minimalist'},
              {title: 'Glassmorphism', value: 'glassmorphism'},
              {title: 'Bold', value: 'bold'},
            ],
            layout: 'radio',
          },
        }),
        defineField({
          name: 'font',
          title: 'Font',
          type: 'string',
          description: 'Optional font name/key, e.g. "Montserrat-Bold". Falls back gracefully if not bundled.',
          options: {
            list: [
              {title: 'Montserrat Bold', value: 'Montserrat-Bold'},
              {title: 'Oswald Bold', value: 'Oswald-Bold'},
              {title: 'Playfair Display', value: 'PlayfairDisplay-Regular'},
            ],
          },
        }),
        defineField({
          name: 'color',
          title: 'Text Color',
          type: 'string',
          description: 'Optional. Hex code (e.g. #FFFFFF) or FFmpeg color name.',
        }),
        defineField({
          name: 'shadow',
          title: 'Force Drop Shadow',
          type: 'boolean',
          description: 'Optional. Leave unset to use the mode/preset default.',
        }),
        defineField({
          name: 'box_opacity',
          title: 'Background Box Opacity',
          type: 'number',
          description: 'Optional. 0 (transparent) to 1 (solid) opacity for the box behind the text.',
          validation: (rule) => rule.min(0).max(1),
        }),
      ],
    }),
    defineField({
      name: 'video_processed',
      title: 'Video Processed',
      type: 'boolean',
      description: 'Check this if a promotional video has already been generated for this tour.',
      initialValue: false,
    }),
    defineField({
      name: 'video_title',
      title: 'Video Title',
      type: 'string',
      description: 'AI-generated title for the rendered promo video. Set automatically by the n8n workflow.',
      readOnly: true,
    }),
    defineField({
      name: 'video_url',
      title: 'Video URL',
      type: 'url',
      description: 'Hosted URL of the rendered promo video. Set automatically by the n8n workflow.',
      readOnly: true,
    }),
  ],
  preview: {
    select: {
      title: 'title',
      media: 'images.0',
      subtitle: 'slug.current',
      style: 'style',
    },
    prepare({title, media, subtitle, style}) {
      return {
        title,
        media,
        subtitle: [subtitle, style].filter(Boolean).join(' · '),
      }
    },
  },
})